language: 
    - python

python:
    - "2.7"
  
before_install:
    pip install --upgrade setuptools
    
# install dependencies
install:
    pip install mitmproxy

# command to run tests
script:
    python Test.py